/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Saved": "已保存",
    "Time": "时间",
    "Warrior": "战士",
    "Working...": "工作中...",
    "World Preview": "世界预览",
    "World Map": "世界地图",
    "Unnamed": "未命名",
    "Scholar": "学者",
    "Stamina": "耐力",
    "Services": "服务",
    "Seed:": "种子:",
    "Scout": "侦察兵",
    "Rest (1hr)": "休息 (1小时)",
    "⏸ Stop": "⏸ 停止",
    "← Back": "← 返回",
    "⛺ Camp": "⛺ 营地",
    "📚 Lexicon": "📚 词典",
    "Actions": "动作",
    "Class": "职业",
    "Class Perks": "职业特权",
    "Continue": "继续",
    "Continue Journey": "继续旅途",
    "Create Your Character": "创建你的角色",
    "dwarf": "矮人",
    "Dwarf": "矮人",
    "Empty": "空",
    "EXP": "经验值",
    "Floor": "层数",
    "Goblin": "哥布林",
    "goblin": "哥布林",
    "Merchant": "商人",
    "Name": "名称",
    "No Target": "无目标",
    "Prestige": "声望",
    "Ranger": "游侠",
    "Reroll World": "重新生成世界",
    "Log": "日志",
    "Iron Company": "钢铁公司",
    "Inventory": "背包",
    "HP": "生命值",
    "Health": "生命值",
    "Half Elf": "半精灵",
    "Agility": "敏捷",
    "elf": "精灵",
    "Elf": "精灵",
    "Human": "人类",
    "human": "人类",
    "Druid": "德鲁伊",
    "druid": "德鲁伊",
    "Idle": "放置",
    "Guilds of Power": "权利公会",
    "-- hexes": "—— 六边形",
    "Activities": "活动",
    "Alignment:": "立场：",
    "Artisan": "工匠",
    "Artisan's Circle": "工匠联盟",
    "Battle Hardened: Start with Combat skill at 5": "战斗强化：战斗技能5点开始",
    "Begin Journey": "开始旅程",
    "Biome": "生物群落",
    "Character Creation": "角色创建",
    "Citizen": "公民",
    "citizen": "公民",
    "Cleric": "牧师",
    "cleric": "牧师",
    "Click to cycle": "点击循环",
    "Debug: Mid-Game State (Testing)": "调试：游戏中期状态（测试）",
    "Discovered Knowledge": "已发现的知识",
    "Dragon-tongue": "龙舌",
    "Enter Name to Begin": "输入名称开始",
    "Ether": "以太",
    "Explorer's League": "探险家联盟",
    "Forge Your Legacy in a World of Intrigue": "在一个充满阴谋的世界中锻造你的遗产",
    "Influence": "影响力",
    "Lexicon": "词典",
    "Mage": "法师",
    "mage": "法师",
    "Mechanist": "机械师",
    "mechanist": "机械师",
    "Mercenary": "雇佣兵",
    "mercenary": "雇佣兵",
    "Merchant's Coalition": "商人联盟",
    "Modal Title": "模态标题",
    "Morning": "早晨",
    "Neutral": "中立",
    "New Game": "新游戏",
    "No Guild (Independent)": "无公会（独立）",
    "Orc": "兽人",
    "orc": "兽人",
    "Paladin": "圣骑士",
    "paladin": "圣骑士",
    "Race": "种族",
    "Rogue": "流氓",
    "rogue": "流氓",
    "Shield Wall: +25% damage reduction when HP below 50%": "盾墙：当HP低于50%时+25%伤害减免",
    "Starting Guild": "初始公会",
    "Stats": "属性",
    "Trust": "信任",
    "Basics": "基础",
    "⛏️ Gathering Resources": "⛏️ 采集资源",
    "🕐 Time & Day Cycle": "🕐 时间 & 每日循环",
    "🚶 Movement & Travel": "🚶 移动 & 旅行",
    "Tips": "提示",
    "Stop Mode": "停止模式",
    "🎣 Coasts: Fish or collect shells\n": "🎣 海岸：捕鱼或收集贝壳\n",
    "The ×number shows total remaining uses nearby\n- Each resource spot has limited uses before it's depleted\n- Depleted resources respawn elsewhere over time\n- Gathering costs stamina and time\n- Higher Prestige gives bonus yield!": "×数字 显示了附近的总剩余使用\n-每个资源点在耗尽之前都有有限的使用\n-随着时间的推移，耗尽的资源在其他地方重生\n-收集成本耐力和时间\n-更高的声望给予奖励产量！",
    ":\n1. Move adjacent to (or onto) a hex with a resource icon\n2. Action buttons appear automatically (e.g., \"🪓 Chop Wood ×5\")\n3. Click an action to start gathering\n4. Wait for the progress bar to complete\n": ": \n1.移动相邻（或上）的十六进制与资源图标\n2.操作按钮自动出现（例如，\“🪓 砍木头 ×5\”）\n3.点击一个动作开始收集\n4.等待进度条完成\n",
    ": Press the time button or Spacebar to pause automatic time. Time only advances when you take actions. After 15 seconds of idle, realtime resumes.\n\nThe day cycles through morning (6-12), afternoon (12-17), evening (17-21), and night (21-6). Night travel is more dangerous and exhausting.": "：按时间键或空格键暂停自动计时。只有你采取行动，时间才会前进。空闲15秒后，实时恢复。一天的周期是上午（6-12）、下午（12-17）、晚上（17-21）和晚上（21-6）。夜间旅行更危险，也更累人。",
    "🌲🌳 Trees: Chop for wood\n- 🪨⛰️ Rocks: Mine for ore and stone\n- 🌿🌸 Plants: Gather herbs and flowers\n- 🐚🎣 Coasts: Fish or collect shells\n": "🌲🌳树木：砍伐木材\n-🪨⛰️岩石：开采矿石和石头\n-🌿🌸植物：收集草本和花朵\n-🐚🎣海岸：收集鱼类或贝壳\n",
    "Mountains: Slower travel, more stamina cost\n- Roads: Faster travel between locations\n- Water: Impassable (use bridges)\n": "山：缓慢的旅行，更多的能量消耗\n-道路：更快的旅行地点之间\n-水：不可通行（使用桥梁）\n",
    ": Moving costs stamina. Rest to recover. Running out of stamina slows you down significantly.": "移动需要耐力。休息以恢复体力。耗尽耐力会显著降低你的速度。",
    ": Time advances automatically (2 minutes every few seconds). The world moves around you.\n": "：时间自动前进（每隔几秒2分钟）。世界围着你转",
    "Click on the map to move. Your character will walk along the path, with each step taking time and stamina.\n": "点击地图移动。你的角色将沿着这条路走下去，每走一步都需要时间和能量",
    "Gathering Resources": "采集资源",
    "How to Gather": "如何采集",
    "Movement & Travel": "移动 & 旅行",
    "Realtime Mode": "实时模式",
    "Resource Icons": "资源图标",
    "Rocks: Mine for ore and stone\n- 🌿🌸 Plants: Gather herbs and flowers\n-": "岩石：开采矿石和石头\n-🌿🌸植物：收集草本植物和花朵\n-",
    "Select an entry to view details": "选择条目以查看详细信息",
    "Terrain Effects": "地形影响",
    "The world is filled with resources you can gather. Look for icons on the map:\n": "这个世界充满了你可以收集的资源。在地图上寻找图标：\n",
    "Time & Day Cycle": "时间和日循环",
    "Time in Etherground flows in two modes:\n": "以太坊的时间有两种流动模式：\n",
    "Trees: Chop for wood\n-": "树：砍木头\n-",
    "Animal Companion: Start with a loyal wolf companion": "动物伙伴：从忠诚的狼伙伴开始",
    "Arcane Study: +50% Ether regeneration rate": "奥术学习：+50%以太回复速度",
    "Automaton: Build mechanical helpers for tasks": "自动化：为任务建造机械助手",
    "Backstab: First attack in combat deals double damage": "背刺：战斗中首次攻击造成双倍伤害",
    "Blessing: Party members gain +10% to all yields": "祝福：团队成员获得+10%的所有收益",
    "Connections: Start with 100 extra gold": "连接：从额外的100金币开始",
    "Divine Protection: Immune to curses and dark magic": "神圣保护：免疫诅咒和黑魔法",
    "Eagle Eye: Discover nearby POIs automatically": "鹰眼：自动发现附近的poi",
    "Efficient: -20% material cost for crafting": "高效：-20%的材料成本制作",
    "Elemental Mastery: Unlock elemental spells earlier": "元素精通：提前解锁元素法术",
    "Healing Aura: Slowly regenerate HP while resting": "治疗光环：休息时缓慢回复HP",
    "Keen Senses: Spot ambushes and hidden dangers": "敏锐的感官：发现埋伏和隐藏的危险",
    "Lay on Hands: Can heal party members using Ether": "施放双手：可以使用以太治疗团队成员",
    "Lockpick: Can access locked areas and containers": "开锁器：可以进入被锁的区域和容器",
    "Lore Master: Identify rare items and artifacts": "学识大师：识别稀有物品和神器",
    "Master Crafter: +25% quality on crafted items": "工艺大师：在制作的物品上+25%的质量",
    "Nature's Bounty: +50% resources from gathering": "自然恩赐：增加50%收集资源",
    "Negotiator: +20% gold from combat and quests": "谈判者：战斗和任务中增加20%的金币",
    "Pathfinder: -30% travel time on roads": "探路者：-30%的旅行时间在道路上",
    "Quick Learner: +50% experience from all sources": "快速学习：+50%的经验从所有来源",
    "Survivalist: -50% stamina cost when traveling": "生存主义者：旅行时消耗50%的耐力",
    "Tinkerer: Can repair and upgrade equipment": "修补匠：可以修理和升级设备",
    "Trade Routes: +30% profit from buying/selling": "贸易路线：买卖利润+30%",
    "Weapon Master: Start with Combat skill at 3": "武器大师：从战斗技能3开始",
    "▶ Play": "▶ 继续",
    "Guilds": "公会",
    "Next →": "下一个 →",
    "◉ Enter ": "◉ 进入",
    "⛺ Make Camp": "⛺ 搭建营地",
    "🌿 Gather Herbs": "🌿 采集草药",
    "🏹 Hunt Game": "🏹 狩猎",
    "💤 Unlit": "💤 未点亮",
    "Cults": "邪教",
    "Light": "点亮",
    "lurk in the shadows, their dark shrines emanating corruption. Some seek their forbidden power... at great cost.": "潜伏在阴影中，他们黑暗的神殿散发着腐败。有些人寻求他们被禁止的力量……代价是巨大的。",
    "order and chaos": "秩序与混乱",
    "Rope": "绳子",
    "seek to protect civilization, offering contracts, training, and purpose. Join their ranks to gain power through honor.": "寻求保护文明，提供合同、培训和目标。加入他们的行列，通过荣誉获得权力。",
    "Unknown Settlement": "未知定居点",
    "Tent": "帐篷",
    "The choice of which path to walk is yours alone.": "走哪条路是你自己的选择。",
    "Torch": "火炬",
    "Travel Rations": "旅行口粮",
    "Waterskin": "革制水袋",
    "Welcome to the Realm": "欢迎来到王国",
    "You arrive at Low gate, ready to begin your journey.": "你到达了低门，准备开始你的旅程。",
    "You awaken in a land torn between": "你在一片分裂的土地上醒来",
    "You packed your survival gear.": "你准备好了生存装备。",
    "Begin Adventure": "开始冒险",
    "stamina": "耐力",
    "Settlements": "定居点",
    "Trade": "贸易",
    "wandering NPCs": "流浪的NPC",
    "- Collect resources automatically": "- 自动采集资源",
    "- Generate income over time": "- 随着时间的推移产生收入",
    "- Protect locations from threats": "- 保护位置免受威胁",
    "A strong following is key to surviving the challenges ahead.": "强大的追随者是应对未来挑战的关键。",
    "as you travel - roads are faster and safer. Rest when needed.": "当你旅行-道路是更快和更安全。必要时休息。",
    "As you travel, you'll encounter": "当你旅行时，你会遇到",
    "at settlements to expand your influence. Assign them to:": "在定居点扩大你的影响力。将它们分配给：",
    "at the bottom guides you to points of interest. Click it to cycle through targets.": "在底部引导你到感兴趣的点。点击它来循环浏览目标。",
    "Building Your Following": "建立你的追随者",
    "compass": "指南针",
    "Dungeons": "地牢",
    "Explore the Unknown": "探索未知世界",
    "Game loaded": "游戏已加载",
    "Gather": "采集",
    "Good luck, traveler. May your journey be legendary.": "祝你好运，旅行者。愿你的旅程充满传奇色彩。",
    "Guard": "守卫",
    "Guard,": "守卫,",
    "Guild halls": "公会大厅",
    "Hire citizens": "雇佣市民",
    "hold treasures and dangers.": "把握财富和危险。",
    "offer rest and trade.": "提供休息和交易。",
    "provide contracts and training.": "提供合同和培训。",
    "The world is vast and filled with secrets.": "世界很大，充满了秘密。",
    "Watch your": "注意你的",
    "who may join your cause.": "谁会加入你的事业。",
    "Economy:": "经济:",
    "Empire of Solis": "索利斯帝国",
    "Faction:": "阵营:",
    "Barracks, Blacksmith": "兵营，铁匠",
    "Population:": "人口:",
    "Theron Whiteaxe is too far away. Move closer!": "塞隆·怀特克斯离我们太远了。再靠近一点！",
    "Town": "小镇",
    "Trading": "交易",
    "Wealth:": "财富:",
    "Wealthy": "富有",
    "Wilderness": "荒野",
    "(Here)": "(这里)",
    "🎣 Fish": "🎣 钓鱼",
    "Hunt Game": "狩猎",
    "Afternoon": "下午",
    "Chop Tree": "砍树",
    "Coast": "海岸",
    "Unknown Dungeon": "未知地下城",
    "Fish": "鱼",
    "Grassland": "草原",
    "Evening": "夜晚",
    "🛒 Trade": "🛒 贸易",
    "🪵 Wood": "🪵 木头",
    "🪨 Stone": "🪨 石头",
    "🪓 Chop Tree": "🪓 砍树",
    "🔦 Torch": "🔦 火炬",
    "🩹 Bandage": "🩹 绷带",
    "💧 Waterskin": "💧 革制水袋",
    "⛺ Tent": "⛺ 帐篷",
    "🎒 Travel Rations": "🎒旅行口粮",
    "Wood": "木头",
    "Stone": "石头",
    "Gold Ring": "金戒指",
    "Hunting": "狩猎",
    "friendly": "友好",
    "Enchanted Amulet": "附魔护身符",
    "Dig for Stone": "挖石头",
    "Cut Emerald": "切割翡翠",
    "Blue Sapphire": "蓝宝石",
    "(Adjacent)": "（相邻）",
    "⚔️ Attack Gemcutter Elara": "⚔️ 攻击宝石切割者艾拉拉",
    "⛏️ Dig for Stone": "⛏️ 挖石头",
    "💰 Sell to Gemcutter Elara": "💰 卖给宝石切割者艾拉拉",
    "Attack Gemcutter Elara": "攻击宝石切割者艾拉拉",
    "Bandage": "绷带",
    "Gemcutter Elara": "宝石切割者艾拉拉",
    "Gemcutter Elara is too far away. Move closer!": "宝石切割者艾拉拉距离过远。走得更近些!",
    "Independent": "独立",
    "Blacksmith, Library": "铁匠、图书馆",
    "Polished Ruby": "抛光红宝石",
    "River Pearl": "珍珠河",
    "Silver Necklace": "银项链",
    "Traveling Jeweler": "旅行的珠宝商",
    "You arrive at High gate, ready to begin your journey.": "你到达高门，准备开始你的旅程。",
    "Your morals are slipping...": "你的道德在堕落...",
    "Gain followers, guild & party members. Earned through volunteering.": "获得追随者，公会和团队成员。通过自愿服务获得。",
    "Higher yields and favorable outcomes. Earned through quests.": "更高的收益和有利的结果。通过任务获得。",
    "Movement speed (+5% per point) and evasion in combat.": "战斗中的移动速度（每点+5%）和闪避。",
    "Relations with guilds, leaders, and locations. Earned through quests.": "与公会、领袖和地点的关系。通过任务获得。",
    "Attack": "攻击",
    "Combat": "战斗",
    "Combat begins!": "战斗开始!",
    "End Turn ⏩": "结束回合 ⏩",
    "Flee": "逃跑",
    "Game Over": "游戏结束",
    "You have fallen in battle...": "你在战斗中失败了...",
    "You Have Fallen": "你陨落了",
    "Your journey ends here.": "你的旅途结束于此。",
    "Wild Boar": "野猪",
    "Thrust": "刺",
    "Slash": "砍",
    "Night time": "夜晚时间",
    "Night": "夜晚",
    "Return to Title": "返回首页",
    "Combat Basics": "战斗基础",
    "ettlements": "定居点",
    "Here!": "这里!",
    "⏱️ Action Window": "⏱️ 动作窗口",
    "🦠 You are now Infected!": "🦠 你现在被感染了！",
    "🩸 You are now Bleeding!": "🩸 你现在流血了！",
    "A Wild Boar appears!": "一只野猪出现了！",
    "Defend": "防御",
    "New resources appeared in the wilderness.": "荒野中出现了新的资源。",
    "Set up camp and rested safely.": "安营扎寨，安全休息。",
    "Pit Viper": "蝮蛇",
    "Game Meat": "猎物肉",
    "← Back to List": "← 返回列表",
    "Locations": "位置",
    "Damage": "伤害",
    "Types": "类型",
    "Your Options": "你的选项",
    ": Based on your weapon, class bonuses, and the enemy's defense. Critical hits deal extra damage.": "：基于你的武器、职业加值和敌人的防御。暴击造成额外伤害。",
    ": Press the time button or Spacebar to pause automatic time. Time only advances when you take actions. After 15 seconds of idle, realtime resumes.": "：按时间键或空格键暂停自动计时。只有你采取行动，时间才会前进。空闲15秒后，实时恢复。",
    ": Rest, Trade, Work, Volunteer, Hire Citizens": "：休息，贸易，工作，志愿者，雇佣公民",
    ": Shops, Taverns, Stables, Guild Halls": "：商店、酒馆、马厩、公会大厅",
    ": Time advances automatically (2 minutes every few seconds). The world moves around you.": "：时间自动前进（每隔几秒2分钟）。世界围着你转。",
    ": Villages, Towns, Cities, Outposts, Ports": "：村庄、城镇、城市、前哨站、港口",
    "• Attack: Deal damage based on your weapon and stats": "• 攻击：基于你的武器和属性造成伤害",
    "• Defend: Reduce incoming damage": "• 防御：减少伤害",
    "• Flee: Attempt to escape (may fail)": "• 逃跑：试图逃跑（可能失败）",
    "• Use Item: Consume potions or use equipment": "• 使用物品：消耗药水或使用装备",
    "Larger settlements have more services and opportunities.": "更大的定居点有更多的服务和机会。",
    "Settlements are safe havens where you can rest, trade, and find work.": "定居点是安全的避风港，你可以在那里休息、交易和找工作。",
    "The day cycles through morning (6-12), afternoon (12-17), evening (17-21), and night (21-6). Night travel is more dangerous and exhausting.": "一天的周期是上午（6-12）、下午（12-17）、晚上（17-21）和晚上（21-6）。夜间旅行更危险，也更累人。",
    "Time in Etherground flows in two modes:": "以太坊中的时间以两种模式流动：",
    "When you encounter enemies, combat begins. Combat is turn-based.": "当你遇到敌人时，战斗就开始了。战斗是回合制的。",
    "DODGE!": "闪避!",
    "A Goblin appears!": "一只哥布林出现了!",
    "Collect Shells": "采集贝壳",
    "Shells": "贝壳",
    "💔 You are now Weakened!": "💔 您现在处于虚弱状态！",
    "🐚 Collect Shells": "🐚 采集贝壳",
    "Danger:": "危险性:",
    "Work": "工作",
    "Warriors": "战士",
    "Settlement": "定居点",
    "Resources:": "资源:",
    "Rangers": "游侠",
    "Citizens": "市民",
    "\"Destroyed in ancient war\"": "“在远古战争中被摧毁”",
    "⚒️ Smithing": "⚒️ 锻造",
    "⚔️ Warriors": "⚔️ 战士",
    "⚕️ Clerical Medicine": "⚕️ 文书医学",
    "🌾 Agriculture": "🌾 农业",
    "🏹 Rangers": "🏹 游侠",
    "🔨 Construction": "🔨 建造",
    "🧵 Tailoring": "🧵 裁剪",
    "Agriculture": "农业",
    "Artifacts": "神器",
    "Attributes": "属性",
    "Caution Advised": "注意事项",
    "Clerical Medicine": "文书医学",
    "Click again to walk to High gate.": "再次点击走到高门。",
    "Condition:": "条件:",
    "Construction": "建造",
    "Facilities": "设施",
    "Hidden remnants": "隐藏的残留物",
    "Hire citizens to help with tasks": "雇佣市民帮忙完成任务",
    "No citizens hired": "没有雇佣公民",
    "No guild membership": "没有公会会员",
    "Rest at Inn": "在旅馆休息",
    "Ruins": "遗迹",
    "Smithing": "锻造",
    "Tailoring": "裁剪",
    "Town Board": "城镇委员会",
    "Town Storage": "城镇仓库",
    "Volunteer": "志愿者",
    "Well-maintained": "维护良好",
    "/day": "/天",
    "💤 Idle": "💤 空闲",
    "📊 Details": "📊 详情",
    "Gather Wood": "采集木头",
    "Mine Stone": "开采石头",
    "Repair Buildings": "修理建筑",
    "Assist Merchants": "协助商人",
    "Available Projects": "可用项目",
    "Blacksmith": "铁匠",
    "Available": "可用",
    "Available for tasks": "可用于任务",
    "Catch Fish": "捕鱼",
    "Clear Pests": "清除害虫",
    "Clear the Roads": "清理道路",
    "Delivery Run": "交付运行",
    "Establish Clinic": "建立诊所",
    "Establish Trade Route": "建立贸易路线",
    "Gather Herbs": "采集草药",
    "Hire": "雇佣",
    "Survey Resources": "资源调查   ",
    "Smithy Work": "铁匠工作",
    "Tailor,": "裁缝,",
    "Tailor": "裁缝",
    "Healer": "治疗师",
    "Healer,": "治疗师,",
    "Farmer": "农夫",
    "Farmer,": "农夫,",
    "Farmer, Healer": "农夫, 治疗师",
    "Ranger, Farmer": "游侠, 农夫",
    "Ranger, Healer": "游侠, 治疗师",
    "Ranger, Guard": "游侠, 守卫",
    "Store": "存入",
    "Take": "取出",
    "Repair Town Walls": "修理城墙",
    "Organize Militia": "组织民兵",
    "Accept": "接受",
    "Build Granary": "建造谷仓",
    "Equipment Upgrades": "装备升级",
    "Horse Rental": "马匹租赁",
    "Merchant Visits": "商人访问",
    "Metal Crafting": "金属加工",
    "Repair": "修理",
    "Room Rental": "房屋租赁",
    "Rumors": "流言",
    "Trade Goods": "交易商品",
    "🏛️ Town Facilities": "🏛️ 城镇设施",
    "🌾 Xavier Deepstorm": "🌾 泽维尔·深风暴",
    "🔨 Ulfric Ironfrost": "🔨 乌弗瑞克·铁霜",
    "Complete Build": "完成建造",
    "combat": "战斗",
    "crafting": "制作",
    "Join": "加入",
    "Join Guild": "加入公会",
    "Locked": "未解锁",
    "magic": "魔法",
    " is now idle": " 现在空闲了",
    " assigned to townTask": " 被分配到了城镇任务",
    "trade": "交易",
    "Work Tasks": "工作任务",
    "Inn": "旅馆",
    "Dismiss": "解雇",
    "Gather Rumors": "搜集流言",
    "Assign citizen...": "分配市民...",
    " has established Construction!": "建立了建筑!",
    " has established Rangers!": "建立了游骑兵！",
    ": Construction established!": "：建造成功！",
    ": Rangers established!": "：游骑兵成立！",
    "Active": "活跃",
    "Active Projects": "活跃项目",
    "Appraise Goods": "评估商品",
    "Build Granary": "建造谷仓",
    "Build Granary": "建造谷仓",
    "Build New Well": "建造新井",
    "Buy and sell goods at better prices": "以更好的价格买卖商品",
    "Construct a well to improve water access": "打一口井以改善取水",
    "Construct storage for food reserves": "建造储存食物的仓库",
    "Corwin Wildward": "科温·沃德",
    "Courier Run": "速递运行",
    "Craft and repair metal equipment": "制造和修理金属装备",
    "Create a trade connection to nearby settlement": "与附近的定居点建立贸易联系",
    "Daily yield potential based on agriculture": "基于农业的每日产量潜力",
    "Daily yield potential based on construction": "基于建筑的日收益潜力",
    "discovery": "发现",
    "Ether Conclave": "以太秘密会议",
    "Fast travel to nearby settlements": "快速前往附近的定居点",
    "Groom Horses": "梳理马匹",
    "Guard Duty": "守卫职责",
    "Haggle Training": "砍价培训",
    "Heal Wounded": "治愈伤口",
    "Hired Ulfric Ironfrost": "雇用乌尔弗里克·铁霜",
    "Hired Xavier Deepstorm": "雇佣泽维尔·深度风暴",
    "Idle - assign from Work, Volunteer, or Quests": "空闲 - 从工作，志愿者，或任务分配",
    "Infrastructure projects to develop the town": "发展城镇的基础设施项目",
    "leather_straps": "皮革带",
    "Map nearby resource locations": "绘制附近的资源位置",
    "Market Square": "市集广场",
    "No economy data available": "暂无可用经济数据",
    "political": "政治",
    "Remove debris and hazards from local roads": "清除当地道路上的碎片和危险物",
    "Repair Buildings": "修理建筑物",
    "Repair Equipment": "修理装备",
    "Smith": "史密斯",
    "Rest and recover, hear rumors": "休养生息，听听流言",
    "Select citizen...": "选择公民…",
    "Serve Guests": "服务客人",
    "Set up a place for healing the sick": "设立一个医治病人的地方",
    "Shadow Council": "影子议会",
    "Smith Apprentice": "铁匠学徒",
    "Stable": "马厩",
    "Storage Shed": "仓库",
    "Store resources safely in town": "将资源安全储存在城镇",
    "Stored Items": "存储物品",
    "Street Patrol": "街头巡逻",
    "Strengthen settlement defenses": "加强定居点防御",
    "Gather Wood!": "收集木材！",
    "Mine Stone!": "挖掘石头！",
    "Repair Buildings!": "修复建筑！",
    "Teach Skills": "传授技能",
    "Train citizens for town defense": "为城镇防御训练市民",
    "Your Inventory": "你的库存",
    "🌿 You are now Entangled!": "🌿 你现在被纠缠上了！",
    "Groom Horses!": "梳理马匹!",
    "⚔️ Combat Basics": "⚔️ 战斗基础",
    ": Rest, Trade, Work, Volunteer, Hire Citizens\n\nLarger settlements have more services and opportunities.": "当前位置休息、贸易、工作、志愿者、雇佣公民\n\n较大的定居点有更多的服务和机会。",
    "Attack: Deal damage based on your weapon and stats\n- Defend: Reduce incoming damage\n- Use Item: Consume potions or use equipment\n- Flee: Attempt to escape (may fail)\n": "攻击：根据你的武器和属性造成伤害\n-防御：减少传入的伤害\n-使用物品：消耗药水或使用装备\n-逃离：试图逃脱（可能失败）\n",
    "Settlements are safe havens where you can rest, trade, and find work.\n": "定居点是安全的避风港，你可以在那里休息、交易和找工作",
    "When you encounter enemies, combat begins. Combat is turn-based.\n": "当你遇到敌人时，战斗就开始了。战斗是回合制的",
    "🏘️ Settlements": "🏘️ 定居点",
    "Herbs": "草药",
    "Specter": "幽灵",
    "Pit Viper, Specter": "辐射, 幽灵",
    "aged_cheese": "成熟的干酪",
    "Gather Herbs!": "采集草药!",
    "simple_tunic": "简单束腰外衣",
    ": Agriculture established!": "：农业已建立！",
    " is now a Apprentice in Construction!": " 现在是建筑学徒！",
    " has established Agriculture!": "建立了农业！",
    "Click to use": "点击使用",
    "equipment": "装备",
    "Extinguish": "扑灭",
    "Extinguished torch.": "扑灭火炬。",
    "Lit a torch.": "点亮火炬。",
    "usable": "可使用",
    "You set up the tent for rest.": "你搭起帐篷休息。",
    "consumable": "消耗品",
    "Cures: poison": "诅咒: 中毒",
    "food (raw)": "食物 (生)",
    "food": "食物",
    "Fresh water for the road": "路上用的淡水",
    "Medicinal herbs for healing": "治疗用草药",
    "Preserved food for journeys": "旅行用的腌制食品",
    "Wild game from hunting": "狩猎的野味",
    "🌿 Herbs": "🌿 草药",
    "Cave Spider": "洞穴蜘蛛",
    "🍖 Game Meat": "🍖 猎物肉",
    "Not enough gold.": "金币不足。",
    "Cave Spider, Goblin, Cave Spider": "洞穴蜘蛛, 哥布林, 洞穴蜘蛛",
    "🤢 You are now Poisoned!": "🤢 你现在中毒了!",
    "Cave Spider and Goblin and Cave Spider appear!": "洞穴蜘蛛、哥布林 和 洞穴蜘蛛 出现了!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Gillkin": "蛤蟆",
    "Mandragora": "曼德拉草",
    "The": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "---": "---",
    "×": "×",
    "⚔️": "⚔️",
    "⚙️": "⚙️",
    "✓": "✓",
    "✝️": "✝️",
    "➤": "➤",
    "⭐": "⭐",
    "🌿": "🌿",
    "🏹": "🏹",
    "🐲": "🐲",
    "👑": "👑",
    "👤": "👤",
    "👹": "👹",
    "👺": "👺",
    "💨": "💨",
    "💪": "💪",
    "💰": "💰",
    "📖": "📖",
    "📚": "📚",
    "📜": "📜",
    "🔨": "🔨",
    "🔮": "🔮",
    "🗝️": "🗝️",
    "🗡️": "🗡️",
    "🗺️": "🗺️",
    "🤝": "🤝",
    "🧔": "🧔",
    "🧝": "🧝",
    "🧝‍♀️": "🧝‍♀️",
    "🛡️": "🛡️",
    "⛏️": "⛏️",
    "🚶": "🚶",
    "🕐": "🕐",
    "⚒️": "⚒️",
    "✨": "✨",
    "🌲": "🌲",
    "🎯": "🎯",
    "🏕️": "🏕️",
    "🐺": "🐺",
    "👁️": "👁️",
    "💚": "💚",
    "💛": "💛",
    "📈": "📈",
    "🔍": "🔍",
    "🔥": "🔥",
    "🔧": "🔧",
    "🤖": "🤖",
    "🦅": "🦅",
    "🙏": "🙏",
    "⛺": "⛺",
    "💧": "💧",
    "🔦": "🔦",
    "🪢": "🪢",
    "🎒": "🎒",
    "❓": "❓",
    "Gityx": "Gityx",
    "👥": "👥",
    "◉": "◉",
    "🐟": "🐟",
    "🎣": "🎣",
    "🪓": "🪓",
    "🦝": "🦝",
    "🩹": "🩹",
    "🪨": "🪨",
    "🪵": "🪵",
    "💎": "💎",
    "🏃": "🏃",
    "🐗": "🐗",
    "💀": "💀",
    "🦠": "🦠",
    "🧙": "🧙",
    "🩸": "🩸",
    "🐍": "🐍",
    "🍖": "🍖",
    "🏘️": "🏘️",
    "🐚": "🐚",
    "💔": "💔",
    "⌘": "⌘",
    "🛏️": "🛏️",
    "📋": "📋",
    "📢": "📢",
    "🏛️": "🏛️",
    "🧵": "🧵",
    "📦": "📦",
    "⚕️": "⚕️",
    "🌾": "🌾",
    "◉": "◉",
    "✕": "✕",
    "◉ ": "◉ ",
    "🏥": "🏥",
    "🏨": "🏨",
    "🍞": "🍞",
    "?": "?",
    "🍺": "🍺",
    "📬": "📬",
    "🐀": "🐀",
    "🐴": "🐴",
    "👂": "👂",
    "💤": "💤",
    "🦌": "🦌",
    "🧭": "🧭",
    "🧱": "🧱",
    "🪣": "🪣",
    "🛒": "🛒",
    "🛣️": "🛣️",
    "🛤️": "🛤️",
    "⬆️": "⬆️",
    "🥬": "🥬",
    "👻": "👻",
    "🐸": "🐸",
    "📿": "📿",
    "🕷️": "🕷️",
    "🤢": "🤢",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Gold: ": "金币: ",
    "Location: ": "位置: ",
    "Version ": "版本 ",
    ":\n- ": ":\n- ",
    ":\n-": ":\n-",
    "Welcome, ": "欢迎, ",
    "Settlement: ": "定居点：",
    "Arrived at ": "到达",
    "Dungeon: ": "地下城：",
    "(Trust: ": "(信任: ",
    "Own: ": "拥有: ",
    "From ": "从",
    "Notable: ": "值得注意: ",
    "Actions: ": "动作: ",
    "Days Survived: ": "生存天数: ",
    "Low gate": "低门",
    "High gate": "高门",
    "Grey ford": "浅滩",
    "Green dale": "绿谷",
    "Low vale": "低谷",
    "High keep": "高堡",
    "Lexicon: \"": "字典: \"",
    "Discovered: ": "已发现: ",
    "Level Reached: ": "达到等级: ",
    "Critical hit! ": "暴击! ",
    "Assigned citizen to: ": "分配市民去: ",
    "Travel Speed: ": "旅行速度: ",
    "Travel Cost Reduction: ": "旅行成本降低: ",
    "Storage Slots: ": "存储槽位: ",
    "Storage Capacity: ": "存储容量: ",
    "Sell Price: ": "出售价格: ",
    "Rest Efficiency: ": "休息效率: ",
    "Rested at High gate ": "在 高门 休息 ",
    "Requires: ": "要求: ",
    "Crafting Speed: ": "制作速度: ",
    "Accepted: ": "已接受: ",
    "⚡ ": "⚡ ",
    "✓ ": "✓ ",
    "⚠ Food shortage: Day ": " 食物短缺：天数 ",
    "Buy Price Reduction: ": "购买价格降低: ",
    "Farmer · Level ": "农夫 · 等级 ",
    "Builder · Level ": "建设者 · 等级 ",
    "Farmer • Lv": "农夫 • 等级",
    "Builder • Lv": "建设者 • 等级",
    "Morale: ": "士气: ",
    "Xavier Deepstorm": "泽维尔·深风暴",
    "Ulfric Ironfrost": "乌弗瑞克·铁霜",
    "Ulfric Ironfrost": "乌尔弗里克·铁霜",
    "Ivar Stagstorm": "伊瓦尔·斯塔斯托姆",
    "Kael Boarhorn": "凯尔·博霍恩",
    "Nessa Duskaxe": "内莎·达克克斯",
    "Petra Elderbrand": "佩特拉·埃尔德布兰德",
    "Roland Ironarrow": "罗兰·铁箭",
    "Sigurd Mossflame": "西格德·苔焰",
    "Ulric Thunderwalker": "乌尔里克·雷行者",
    "Valdis Swiftstrider": "瓦尔狄斯·疾行者",
    "Wynne Oakwood": "韦恩·奥克伍德",
    "Wynne Stareye": "韦恩·斯塔耶",
    "Wynne Trueheart": "韦恩·特鲁哈特",
    "Zara Whiteaxe": "扎拉·怀特克斯",
    "Currently: ": "当前: ",
    "Task Complete: ": "任务完成: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    " started training: ": " 开始训练: ",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " Ranger": "游侠",
    " hexes away)": " 六边形剩余)",
    "% success)": "% 几率)",
    " Warrior": " 战士",
    "\" discovered!": "\" 已被发现!",
    "Low gate": "低门",
    "High gate": "高门",
    "Grey ford": "浅滩",
    "Green dale": "绿谷",
    "Low vale": "低谷",
    "High keep": "高堡",
    " blocks your path!": " 挡住了你的去路！",
    " attacks!": " 发起了攻击!",
    " · Dormant": " · 睡眠",
    " · Developing": " · 开发中",
    " · Fledgling": " · 新手",
    " • Farmer": " • 农夫",
    " • Guard": " • 守卫",
    " • Smith": " • 铁匠",
    " • Tailor": " • 裁缝",
    " • Builder": " • 建设者",
    " ⭐⭐⭐": " ⭐⭐⭐",
    " ⭐⭐": " ⭐⭐",
    " ⭐": " ⭐",
    " (Farmer)": "（农民）",
    " (Builder)": "（建设者）",
    " block your path!": " 挡住了你的去路!",
    " caught you stealing!": " 抓到你偷东西！",
    " fought you off!": " 击退了你！",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^😊 ([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)kg$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)g$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^⚡([\d\.,]+)$/,
    /^✨([\d\.,]+)$/,
    /^⚒️ ([\d\.,]+)$/,
    /^⚔️ ([\d\.,]+)$/,
    /^🌾 ([\d\.,]+)$/,
    /^⚕️ ([\d\.,]+)$/,
    /^🏹 ([\d\.,]+)$/,
    /^👥 ([\d\.,]+)$/,
    /^🔨 ([\d\.,]+)$/,
    /^🧵 ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You attack (.+)!$/, '你攻击了 $1!'],
    [/^Attacked (.+) \((.+) alignment\)$/, '你攻击了 $1 ($2 立场)!'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) dodged (.+)\'s attack!$/, '$1 躲开了 $2 的攻击!'],
    [/^(.+) attacks (.+) for (.+) damage! (.+) is defeated!$/, '$1 攻击了 $2 并造成 $3 伤害! $4 被击败了!'],
    [/^(.+) attacks (.+) for (.+) damage!$/, '$1 攻击了 $2 并造成 $3 伤害!'],
    [/^🤢 Poisoned deals (.+) damage!$/, '🤢 中毒 造成了 $3 伤害!'],
    [/^🩸 Bleeding deals (.+) damage!$/, '🩸 流血 造成了 $1 伤害!'],
    [/^🦠 Infected deals (.+) damage!$/, '🦠 感染 造成了 $1 伤害!'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.,]+)g$/, '+$1 金币'],
    [/^\(\-([\d\.,]+)g\)$/, '(-$1 金币)'],
    [/^💰 \+([\d\.,]+)g\/day$/, '+$1 金币/天'],
    [/^💰 \+([\d\.,]+)\/day$/, '+$1 /天'],
    [/^\+([\d\.,]+) HP$/, '+$1 生命值'],
    [/^\+([\d\.,]+) STA$/, '+$1 耐力'],
    [/^\+([\d\.,]+) SP$/, '+$1 耐力点'],
    [/^\+([\d\.,]+) HP, \+([\d\.,]+) SP$/, '+$1 生命值, +$2 耐力点'],
    [/^\+([\d\.,]+) HP, Cures: poison$/, '+$1 生命值, 诅咒: 中毒'],
    [/^\+([\d\.,]+) trust, \+([\d\.,]+) prestige$/, '+$1 信任, +$2 声望'],
    [/^\+([\d\.,]+) trust, \+([\d\.,]+) prestige, \+([\d\.,]+) influence$/, '+$1 信任, +$2 声望, +$3 影响力'],
    [/^\+([\d\.,]+)g, \+([\d\.,]+) trust, \+([\d\.,]+) prestige, \+([\d\.,]+) influence$/, '+$1 金币, +$2 信任, +$3 声望, +$4 影响'],
    [/^\+([\d\.,]+) trust, \+([\d\.,]+) influence$/, '+$1 信任, +$2 影响力'],
    [/^([\d\.,]+) wood, ([\d\.,]+) stone$/, '$1 木头, $2 石头'],
    [/^([\d\.,]+) more Fish available here$/, '$1 鱼在这里可用'],
    [/^([\d\.,]+) more Shells available here$/, '$1 贝壳在这里可用'],
    [/^([\d\.,]+) more Herbs available here$/, '$1 草药在这里可用'],
    [/^([\d\.,]+) more Stone available here$/, '$1 石头在这里可用'],
    [/^([\d\.,]+) more Game Meat available here$/, '$1 猎物肉在这里可用'],
    [/^([\d\.,]+) more Wood available here$/, '$1 木头在这里可用'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) hexes$/, '$1 六边形'],
    [/^([\d\.,]+) hexe$/, '$1 六边形'],
    [/^([\d\.,]+) hex$/, '$1 六边形'],
    [/^\(([\d\.,]+) new!\)$/, '($1 新!)'],
    [/^\(\+([\d\.,]+) from facilities\)$/, '(+$1 来自 设施)'],
    [/^Hire \(([\d\.,]+)\)$/, '雇佣 ($1)'],
    [/^Join \(([\d\.,]+)\)$/, '加入 ($1)'],
    [/^([\d\.,]+)g\/day$/, '$1 金币/天'],
    [/^([\d\.,]+)h • ([\d\.,]+)g$/, '$1小时 • $2金币'],
    [/^([\d\.,]+)h • \+([\d\.,]+)g$/, '$1小时 • +$2金币'],
    [/^([\d\.,]+)h • \+([\d\.,]+)g, \+([\d\.,]+) trust$/, '$1小时 • +$2金币, +$3 信任'],
    [/^([\d\.,]+)h • ([\d\.,]+)g, \+([\d\.,]+) prestige$/, '$1小时 • $2金币, +$3 声望'],
    [/^([\d\.,]+)x • \+([\d\.,]+)g$/, '$1x • +$2金币'],
    [/^([\d\.,]+)x • \+([\d\.,]+)g, \+([\d\.,]+) trust$/, '$1x • +$2金币, +$3 信任'],
    [/^([\d\.,]+)x • \+([\d\.,]+)g, \+([\d\.,]+) influence$/, '$1x • +$2金币, +$3 影响力'],
    [/^([\d\.,]+)x • \+([\d\.,]+)g, \+([\d\.,]+) prestige$/, '$1x • +$2金币, +$3 声望'],
    [/^([\d\.,]+)h • Free$/, '$1小时 • 免费'],
    [/^([\d\.,]+) • construction ([\d\.,]+)$/, '$1 • 建造 $2'],
    [/^([\d\.,]+) • agriculture ([\d\.,]+)$/, '$1 • 农业 $2'],
    [/^: ([\d\.,]+) item\(s\) crafted \(([\d\.,]+)g\)$/, ': $1 物品已制作 ($2金币)'],
    [/^([\d\.,]+) available$/, '$1 可用'],
    [/^([\d\.,]+) people died of starvation in $/, '$1 人死于饥饿在 '],
    [/^([\d\.,]+) hex \[([\d\.,]+)\/([\d\.,]+)\]$/, '$1 六边形 [$2/$3]'],
    [/^([\d\.,]+) hexe \[([\d\.,]+)\/([\d\.,]+)\]$/, '$1 六边形 [$2/$3]'],
    [/^([\d\.,]+) hexes \[([\d\.,]+)\/([\d\.,]+)\]$/, '$1 六边形 [$2/$3]'],
    [/^Day ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '天数 $1，$2:$3'],
    [/^(.+) Lv.([\d\.,]+) \- Day ([\d\.,]+)$/, '$1 等级$2 - 天 $3'],
    [/^Traveling to High gate \(([\d\.,]+) min\)$/, '旅行到 高门 ($1 分钟)'],
    [/^Lv.([\d\.,]+)$/, '等级 $1'],
    [/^Shells • ([\d\.,]+) stamina$/, '贝壳 • $1 耐力'],
    [/^Wood • ([\d\.,]+) stamina$/, '木头 • $1 耐力'],
    [/^Herbs • ([\d\.,]+) stamina$/, '草药 • $1 耐力'],
    [/^Stone • ([\d\.,]+) stamina$/, '石头 • $1 耐力'],
    [/^Fish • ([\d\.,]+) stamina$/, '鱼 • $1 耐力'],
    [/^Game Meat • ([\d\.,]+) stamina$/, '猎物肉 • $1 耐力'],
    [/^Took ([\d\.,]+)x Bandage from storage$/, '从仓库取出 $1x 绷带'],
    [/^Took ([\d\.,]+)x Wood from storage$/, '从仓库取出 $1x 木头'],
    [/^Took ([\d\.,]+)x Stone from storage$/, '从仓库取出 $1x 石头'],
    [/^Stored ([\d\.,]+)× Bandage$/, '存入 $1x 绷带'],
    [/^Stored ([\d\.,]+)× Stone$/, '存入 $1x 石头'],
    [/^Stored ([\d\.,]+)× Wood$/, '存入 $1x 木头'],
    [/^Stored ([\d\.,]+)× Shells$/, '存入 $1x 贝壳'],
    [/^Gathered ([\d\.,]+)x Herbs$/, '获得了 $1x 草药'],
    [/^Gathered ([\d\.,]+)x Shells$/, '获得了 $1x 贝壳'],
    [/^Gathered ([\d\.,]+)x Fish$/, '获得了 $1x 鱼'],
    [/^Gathered ([\d\.,]+)x Stone$/, '获得了 $1x 石头'],
    [/^Gathered ([\d\.,]+)x Game Meat$/, '获得了 $1x 猎物肉'],
    [/^Gathered ([\d\.,]+)x Wood$/, '获得了 $1x 木头'],
    [/^⏱️ ([\d\.,]+)s$/, '⏱️ $1秒'],
    [/^Recovered: \+([\d\.,]+) HP, \+([\d\.,]+) Stamina, \+([\d\.,]+) Ether$/, '恢复了: +$1 生命值, +$2 耐力, +$3 以太'],
    [/^Used 🍖 Game Meat \(\+([\d\.,]+) HP, \+([\d\.,]+) SP\)$/, '使用了 🍖 猎物肉 (+$1 生命值, +$2 耐力点)'],
    [/^Round ([\d\.,]+)$/, '回合 $1'],
    [/^Age ([\d\.,]+)$/, '年龄 $1'],
    [/^Age ([\d\.,]+) •$/, '年龄 $1 •'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^🌾 agriculture ([\d\.,]+)$/, '🌾 农业 $1'],
    [/^⚒️ smithing ([\d\.,]+)$/, '⚒️ 铁匠 $1'],
    [/^🔨 construction ([\d\.,]+)$/, '🔨 建造 $1'],
    [/^🧵 tailoring ([\d\.,]+)$/, '🧵 裁剪 $1'],
    [/^⚔️ warriors ([\d\.,]+)$/, '⚔️ 战士 $1'],
    [/^⚕️ medicine ([\d\.,]+)$/, '⚕️ 医学 $1'],
    [/^warriors ([\d\.,]+)$/, '战士 $1'],
    [/^Town Citizens \(([\d\.,]+) available\)$/, '城镇市民 ($1 可用)'],
    [/^Need ([\d\.,]+) wood$/, '需要 $1 木头'],
    [/^ completed: Groom Horses \(\)$/, ' 完成了: 梳理马匹 ()'],
    [/^ completed: Groom Horses \(\+([\d\.,]+)g, \+([\d\.,]+) trust\)$/, ' 完成了: 梳理马匹 (+$1金币, +$2 信任)'],
    [/^ completed: Gather Herbs \(\+([\d\.,]+)g, \+([\d\.,]+) trust\)$/, ' 完成了: 采集草药 (+$1金币, +$2 信任)'],
    [/^ completed: Gather Wood \(\+([\d\.,]+)g, \+([\d\.,]+) trust\)$/, ' 完成了: 采集木头 (+$1金币, +$2 信任)'],
    [/^ completed: Mine Stone \(\+([\d\.,]+)g, \+([\d\.,]+) trust\)$/, ' 完成了: 开采石头 (+$1金币, +$2 信任)'],
    [/^ completed: Repair Buildings \(\+([\d\.,]+) trust, \+([\d\.,]+) prestige\)$/, ' 完成了: 修理建筑 (+$1 信任, +$2 声望)'],
    [/^: Construction Level ([\d\.,]+)!$/, ': 建造 等级 $1!'],
    [/^Value: ([\d\.,]+)g$/, '价值: $1 金币'],
    [/^Gemcutter Elara: Trust \+([\d\.,]+) \(good trade\)$/, '宝石切割者艾拉拉: 信任 +$1 (不错的买卖)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Dawn of Day ([\d\.,]+)$/, '第 $1 天 黎明'],
    [/^ is experiencing food shortage \(Day ([\d\.,]+)\)$/, ' 正在经历食物短缺 (天数 $1)'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^([\d\.,]+) \/ ([\d\.,]+) XP$/, '$1 \/ $2 经验值'],
    [/^([\d\.,]+)\/([\d\.,]+) wood$/, '$1 \/ $2 木头'],
    [/^([\d\.,]+)\/([\d\.,]+) stone$/, '$1 \/ $2 石头'],
    [/^([\d\.,]+)\/([\d\.,]+) items$/, '$1 \/ $2 物品'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) discovered \((.+)\)$/, '$1 已发现 ($2)'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);